name: itinere
baseurl: /itinere
description: Describe HTTP REST/JSON endpoints
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.0+25-e3015e51
org: net.vectos
markdown: kramdown
